FROM curlimages/curl:8.6.0 as build

ARG ARCH=amd64

WORKDIR /app

RUN curl -L "https://github.com/theandrew168/pg2s3/releases/download/v0.2.0/pg2s3_linux_$ARCH.tar.gz" -o pg2s3.tar.gz

RUN tar -zxf pg2s3.tar.gz

FROM postgres:16

RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates

COPY --from=build /app/pg2s3 /bin/pg2s3

ENTRYPOINT  [ "/bin/pg2s3" ]
