FROM ubuntu:22.04

WORKDIR /app
RUN apt update -y && apt install -y curl tar \
  && curl --proto '=https' --tlsv1.2 -fOL https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.91.0/otelcol-contrib_0.91.0_linux_amd64.tar.gz \
  && tar -xvf otelcol-contrib_0.91.0_linux_amd64.tar.gz \
  && rm otelcol-contrib_0.91.0_linux_amd64.tar.gz
RUN chmod a+x ./otelcol

ENTRYPOINT ["/app/otelcol", "--config", "/app/config.yaml"]
